git:
  quiet: true
  depth: false
notifications:
  email: false
language: java
jdk: openjdk11
install: true
env:
  global:
  - TERM=dumb
addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - bash
    - curl
before_install:
- |
  if [[ ! -f ~/.local/daggerok/main.bash ]] ; then
    mkdir -p ~/.local/daggerok
    curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash > ~/.local/daggerok/main.bash
  fi
- source ~/.local/daggerok/main.bash
- stop_any 5432 5672 27017 8080 8000 8081 80 80
jobs:
  include:
  - stage: test
    name: versions updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
  - ~/.m2
  - ~/.local/daggerok
  packages: true
