name: CI
on: [push]
env:
  CI: 'true'
jobs:
  tests:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: java-${{ matrix.java }} tests
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: cd $GITHUB_WORKSPACE && ./mvnw
  plain-java-route:
    strategy:
      matrix:
        java: [11,14]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: java-${{ matrix.java }} plain-java-route tests
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/mvnw') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: cd $GITHUB_WORKSPACE && ./mvnw clean compile exec:java -f plain-java-route
    - run: sudo apt-get install tree
    - run: tree $GITHUB_WORKSPACE/target
    - run: cat $GITHUB_WORKSPACE/target/messages/*/*
